#!/bin/bash
ln -s "$(realpath .vimrc)" "$HOME/"
ln -s "$(realpath .tmux.conf)" "$HOME/"
ln -s "$(realpath .tmuxline.conf)" "$HOME/"
ln -s "$(realpath .zshrc)" "$HOME/"
ln -s "$(realpath zsh-custom/ninja)" "$HOME/.oh-my-zsh/custom/plugins/"
ln -s "$(realpath .vim/)" "$HOME/"
ln -s "$(realpath .gitconfig)" "$HOME/"
ln -s "$(realpath .gitignore_global)" "$HOME/"
